---
id: sendData
name: sendData
description: sendData
response-description: sendData
parameters:
- name: 12
  type: OBJECT
  required: true
  description: привет
  properties:
  - name: hello
    type: NUMBER
    required: true
    description: hello
    properties: null
    items: null
  items: null
