---
id: humanize
name: humanize
description: 123
response-description: 123
parameters:
- name: querysda
  type: STRING
  required: true
  description: qw3
  properties: null
  items: null
language: PYTHON
