---
id: assert
name: assert
description: assert
response-description: 1234
parameters:
- name: query
  type: STRING
  required: true
  description: "Термин на английском языке, по которому нужно найти статьи"
  properties: null
  items: null
language: JAVASCRIPT
