---
id: sendData
name: sendData
description: sendData
response-description: 1
parameters:
- name: hi
  type: CREDENTIAL
  required: true
  description: привет
  properties: null
  items: null
- name: test
  type: INTEGRATION_RAG
  required: false
  description: cb
  properties: null
  items: null
- name: bool
  type: BOOLEAN
  required: true
  description: "true"
  properties: null
  items: null
