---
id: clamp
name: clamp
description: clamp
response-description: 123
parameters:
- name: query
  type: STRING
  required: true
  description: 123
  properties: null
  items: null
language: JAVASCRIPT
